export const ActionTypes = {
    GENERAL_ADDING: "GENERAL_ADDING",
    GENERAL_ADDING_COMPLETE: "GENERAL_ADDING_COMPLETE",
    ADMIN_LOGGED: "ADMIN_LOGGED",
    ADMIN_LOGOUT: "ADMIN_LOGOUT",
    CHANGING_EXPIRY_DATE: "CHANGING_EXPIRY_DATE",
    CHANGED_EXPIRY_DATE: "CHANGED_EXPIRY_DATE",
    SELLER_REGISTERING: "SELLER_REGISTERING",
    SELLER_REGISTERING_COMPLETED: "SELLER_REGISTERING_COMPLETED",
    PASSWORD_SHOW : "PASSWORD_SHOW",
    PASSWORD_HIDE: "PASSWORD_HIDE"
};